### ISSUE TITLE
Add to Cake website

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/Cake.OctoDeploy#4]
# Description
Listing on Cake website makes it easy to know how to use the package

# Tasks
- Add cake-contrib user to Nuget
- Add details to Cake website repo

**Comment by gep13** [comment]
@DeadlyEmbrace it is great to see that you have created this issue!  Are you in a position to do either of these things?  Thanks!

**Comment by DeadlyEmbrace** [comment]
@gep13 😄 Yes, I'll do it over the weekend. Been meaning to do it for a while, just got carried away with other things

**Comment by DeadlyEmbrace** [comment]
@gep13 I've added cake-contrib as an owner on Nuget, will have the website updated by Sunday

**Comment by gep13** [comment]
>@DeadlyEmbrace said...
I've added cake-contrib as an owner on Nuget, will have the website updated by Sunday

Perfect, thank you very much!

**Comment by gep13** [comment]
Perfect, once you send the PR to the website, I will review.

**Comment by DeadlyEmbrace** [comment]
@gep13 Ah, this has already been done, see [here](https://github.com/cake-build/website/pull/304)
It's actually already [deployed](http://cakebuild.net/dsl/octodeploy/) too
I just closed the issue as it didn't seem to be in the mood to happen by itself. 😄

**Comment by gep13** [comment]
Ah, gotcha. Sorry, missed that one.  Thanks for getting back to me!

**Comment by DeadlyEmbrace** [comment]
No worries. 😄
