### ISSUE TITLE
Error occurs while trying to use the plugin

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/Cake.OctoDeploy#9]
Hi, I just tried it out. If I use

PublishReleaseWithArtifact(
			tag,
			releaseTitle,
			releaseNotes,
			draftRelease,
			preRelease,
			artifactPath,
			artifactName,
			artifactMimeType,
			octoSettings);
with an #addin nuget:?package=Cake.OctoDeploy at the top I get the following error:
Error: One or more errors occurred. (Could not load file or assembly 'Octokit, Version=0.24.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.)

If I add an #addin nuget:?package=Octokit before the #addin nuget:?package=Cake.OctoDeploy I get just an Error: One or more errors occurred. (Not Found)

Any idea where the problem could be? If you need to see the whole build script you can find it here: https://github.com/secana/PeNet/blob/cake/build.cake (bit ugly because not finished and cleaned up)

**Comment by secana** [comment]
As soon as you rolled out a new version I'm going to try it and report back. Regards, secana.

**Comment by DeadlyEmbrace** [comment]
OK, I've rolled out an updated version that seems to work, should be available on Nuget shortly.
Apologies for taking so long to get around to this.

**Comment by secana** [comment]
I just tried it out. The error 
``` 
Error: One or more errors occurred. (Could not load file or assembly 'Octokit, Version=0.24.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.)
```
is fixed. 

I'm still getting the `Error: One or more errors occurred. (Not Found)`. I guess I'm using it wrong. Do you have any idea what is "Not Found". The artifact is definitely there.

**Comment by DeadlyEmbrace** [comment]
Use only 'PeNet' for your repository in settings rather than the full URL. Octokit only uses the owner and repository name to build up the URL (as it is geared only toward Github)
Give that a whirl and give me a shout if you still have issues.

Given the error it seems it might be wise for me to expand the errors that get produced, that one really isn't very useful. Might also need to update the docs if it isn't clear.

**Comment by secana** [comment]
It worked. Awesome! Thx @DeadlyEmbrace.
